apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kibana-oss-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "kibana-oss-app.fullname" . }}-role
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kibana-oss-app.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kibana-oss-app.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "kibana-oss-app.fullname" . }}
  namespace: {{ .Release.Namespace }}